### ISSUE TITLE
Error at the import

### ISSUE THREAD

**Issue by AlexSpss** [tpartner/LimeSurvey-Slider-Controls-6x#1]
Hello,

I'm trying to use this package and it seams to not work properly. I'm using LimeSurvey online version 5.6.8. When I import the file .ZIP in the Theme menu, this error pop up :

![image](https://user-images.githubusercontent.com/127225271/223469034-20df9887-04df-4eb7-866d-9e8bb70ded42.png)

Is there a way to make it work?

Thank you!

**Comment by tpartner** [comment]
1) Why are you trying to use a theme for LimeSurvey 6.x in your 5.x version? You need to use this - https://github.com/tpartner/LimeSurvey-Slider-Controls-5x

2) Please follow the instructions EXACTLY.

![capture-2](https://user-images.githubusercontent.com/1437729/223476873-e85224c7-6820-4cfb-9ae6-18b90a0b874d.png)

**Comment by AlexSpss** [comment]
Thank you! I'll check it out! It work right now!
