### ISSUE TITLE
Slider and numeric imput issue

### ISSUE THREAD

**Issue by Arnaud10H** [tpartner/LimeSurvey-Slider-Controls-6x#2]
Hello,

Many thanks with the slider control.
I try to use it on Limesurvey 6.1

I dont have the slider, only the text and the button.
See attached screenshot :

![image](https://github.com/tpartner/LimeSurvey-Slider-Controls-6x/assets/117773343/83d78b00-5699-4d8f-8662-715471788146)

I tryed to create a new question manually, or import the .lss demo file, not better.

Many thanks

ADI

**Comment by tpartner** [comment]
Fixed.

- https://github.com/tpartner/LimeSurvey-Slider-Controls-6x/commit/51e02601d63cffb6bed4a7eba4100bba34c01c52
- https://github.com/tpartner/LimeSurvey-Slider-Controls-6x/commit/988a2153fd0c77d9d5f15faa816cdaba8d5a1810

**Comment by Arnaud10H** [comment]
Many thanks ☺️

Le mer. 31 mai 2023, 20:53, Tony Partner ***@***.***> a
écrit :

**Comment by Arnaud10H** [comment]
Hello again,
I made some test last night!
When i create a new survey, or import the demo .lss
Now i have the slider but i dont have the minus and plus button anymore.

See attached screenshot

**_Demo .LSS Import:_**
![Capture d'écran 2023-06-01 094200](https://github.com/tpartner/LimeSurvey-Slider-Controls-6x/assets/117773343/8610ed75-5a04-4765-9708-c06984da14ee)

**_Create Slider question manually:_**
![2023-06-01 09_47_07-Demo - Question Theme - Slider Control Buttons (6 x)](https://github.com/tpartner/LimeSurvey-Slider-Controls-6x/assets/117773343/61cfd4ec-46b7-4066-a9b5-5bb20876d41b)

I have to set up this tool in my company, to dematerialize the production and quality documents of the company.
This is the only function "outside" limesurvey useful for our project.
We will also look for a partner for the maintenance of the debian 11 server, limesurvey ;)
Thank you very much for the responsiveness!

**Comment by tpartner** [comment]
I cannot reproduce that problem, can you provide a link to as sample survey?

**Comment by Arnaud10H** [comment]
Hello,

I try with 6x on LS6 install, also tryed with 5x on LS5.
I made fresh install LS, same issue.
I also installed with hosting CPANEL solution, the only one exposed to internet ;)) so i can give you remote access, same issue here, sliders without button after the fixes
https://github.com/tpartner/LimeSurvey-Slider-Controls-6x/commit/51e02601d63cffb6bed4a7eba4100bba34c01c52
https://github.com/tpartner/LimeSurvey-Slider-Controls-6x/commit/988a2153fd0c77d9d5f15faa816cdaba8d5a1810

Remote access will be send by email, can you provide me an email please ?

Many thanks again

**Comment by Arnaud10H** [comment]
![image](https://github.com/tpartner/LimeSurvey-Slider-Controls-6x/assets/117773343/5b3607c8-c66c-4a0b-b44d-7fbc9bd3f180)

Installed with .zip and extension manager (GUI way), for CPanel install.
Tryed both CLI and GUI on our private VM servers.

**Comment by tpartner** [comment]
Contact me at tpartner99@gmail.com

**Comment by Arnaud10H** [comment]
I added you to my online test system, LimeSurvey Version 6.1.0+230522.
access to the demo slider and my own test, for your tpartner user.
I send you credentials with email right now
Many thanks again

**Comment by tpartner** [comment]
I did not receive the email but I am away until next Tuesday.

**Comment by Arnaud10H** [comment]
Sended from my personnal email last night 11:30 GMT +1

**Comment by tpartner** [comment]
I have tested again on my system and cannot reproduce the problem.

The access credentials you sent via email do not work.
